version: '3'
services:
  lamp:
    build:
        context: .
    volumes:
      - ./:/app:delegated
      - db_data:/var/lib/mysql
    ports:
      - '80:80'
      - '3306:3306'
    stdin_open: true
    tty: true

volumes:
  db_data: {}